User.create(name: "ben", email: "Ben@Hotmail.com", password_digest: BCrypt::Password.create('123456'), username: "ben", location: "London", bio: "You’ll never be as lazy as whoever named the fireplace.")
User.create(name: "bryn", email: "Bryn10@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "bryn", location: "London", bio: "I would like to give thanks to the brave men and women who died a long time ago tasting which plants were edible and which plants were not.")
User.create(name: "amy", email: "Amy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "amy", location: "Cape Town", bio: "Pick any number. Multiply it by two. Now add 12 to it. Divide it by 3. Now change it to 10. That’s how many seconds you just wasted.")
User.create(name: "alex", email: "Alex@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "alex", location: "Bournemouth", bio: "How come Dora calls herself an “explorer” but travels exclusively through mapped territories?")
User.create(name: "lee", email: "Lee@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "lee", location: "Glasgow", bio: "Just remember, if the world didn’t suck, we’d all fall off.")
User.create(name: "lili", email: "Lili@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "lili", location: "London", bio: "I don’t know why people dislike jury duty. I think being able to play god with others’ lives sounds fun!
– How I got out of jury duty")
User.create(name: "mustapha", email: "Mustapha@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "mustapha", location: "Dubai", bio: "How many different animals did we have to jump on the backs of before we discovered horses were cool with it?")
User.create(name: "bruno", email: "Bruno@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "bruno", location: "London", bio: "Somewhere in this world, someone is pulling on a door that says 'PUSH.'")
User.create(name: "rikesh", email: "Rikesh@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "rikesh", location: "London", bio: "There’s no killer app I haven’t run / At Pascal, well, I’m number 1 / Do vector calculus just for fun / I ain’t got a gat but I got a soldering gun")
User.create(name: "billy", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "billy", location: "London", bio: "Schrodinger’s Cat walks into a bar… and doesn’t.")
User.create(name: "charles", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "charles", location: "London", bio: "What did Jay-Z call his girlfriend before getting married? Feyoncè.")
User.create(name: "susan", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "susan", location: "London", bio: "A perfectionist walked into a bar...apparently, the bar wasn’t set high enough.")
User.create(name: "batman", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "batman", location: "London", bio: "Did you hear about the crook who stole a calendar? He got twelve months.")
User.create(name: "ronaldo", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "ronaldo", location: "London", bio: "I own the world's worst thesaurus. Not only is it awful, it's awful.")
User.create(name: "pikachu", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "pikachu", location: "London", bio: "The world tongue-twister champion just got arrested. I hear they're gonna give him a really tough sentence.")
User.create(name: "leeroy", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "leeroy", location: "London", bio: "So what if I don't know what 'Armageddon' means? It's not the end of the world.")
User.create(name: "sasuke", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "sasuke", location: "London", bio: "What's the difference between a good joke and a bad joke timing.")
User.create(name: "flyboy", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "flyboy", location: "London", bio: "I hate Russian dolls, they're so full of themselves.")
User.create(name: "jericho", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "jericho", location: "London", bio: "The best thing about good old days is that we were neither good nor old.")
User.create(name: "jesus", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "jesus", location: "London", bio: "Do I lose when the police officer says papers and I say scissors?")
User.create(name: "purple", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "purple", location: "London", bio: "A lot of people cry when they cut onions. The trick is not to form an emotional bond.")
User.create(name: "truck", email: "Billy@Hotmail.com", password_digest: BCrypt::Password.create('1234'), username: "truck", location: "London", bio: "I wrote a song about a tortilla. Well actually, it’s more of a wrap.")




Language.create(name: "Ruby")
Language.create(name: "Javascript")
Language.create(name: "React")
Language.create(name: "Rails")
Language.create(name: "CSS")
Language.create(name: "HTML")
Language.create(name: "Python")
Language.create(name: "C")
Language.create(name: "PHP")
Language.create(name: "Angular")





Langlink.create(user: User.find(1), language: Language.find(1))
Langlink.create(user: User.find(1), language: Language.find(3))
Langlink.create(user: User.find(1), language: Language.find(5))
Langlink.create(user: User.find(2), language: Language.find(2))
Langlink.create(user: User.find(2), language: Language.find(4))
Langlink.create(user: User.find(2), language: Language.find(6))
Langlink.create(user: User.find(3), language: Language.find(3))
Langlink.create(user: User.find(3), language: Language.find(5))
Langlink.create(user: User.find(3), language: Language.find(7))
Langlink.create(user: User.find(4), language: Language.find(4))
Langlink.create(user: User.find(4), language: Language.find(6))
Langlink.create(user: User.find(4), language: Language.find(8))
Langlink.create(user: User.find(5), language: Language.find(5))
Langlink.create(user: User.find(5), language: Language.find(7))
Langlink.create(user: User.find(5), language: Language.find(9))
Langlink.create(user: User.find(6), language: Language.find(6))
Langlink.create(user: User.find(6), language: Language.find(8))
Langlink.create(user: User.find(6), language: Language.find(9))
Langlink.create(user: User.find(7), language: Language.find(7))
Langlink.create(user: User.find(7), language: Language.find(9))
Langlink.create(user: User.find(7), language: Language.find(1))
Langlink.create(user: User.find(8), language: Language.find(8))
Langlink.create(user: User.find(8), language: Language.find(10))
Langlink.create(user: User.find(8), language: Language.find(2))
Langlink.create(user: User.find(9), language: Language.find(9))
Langlink.create(user: User.find(9), language: Language.find(1))
Langlink.create(user: User.find(9), language: Language.find(3))
Langlink.create(user: User.find(10), language: Language.find(10))
Langlink.create(user: User.find(10), language: Language.find(2))
Langlink.create(user: User.find(10), language: Language.find(4))
Langlink.create(user: User.find(11), language: Language.find(6))
Langlink.create(user: User.find(11), language: Language.find(2))
Langlink.create(user: User.find(11), language: Language.find(3))
Langlink.create(user: User.find(12), language: Language.find(6))
Langlink.create(user: User.find(12), language: Language.find(8))
Langlink.create(user: User.find(12), language: Language.find(9))
Langlink.create(user: User.find(13), language: Language.find(7))
Langlink.create(user: User.find(13), language: Language.find(10))
Langlink.create(user: User.find(13), language: Language.find(1))
Langlink.create(user: User.find(14), language: Language.find(10))
Langlink.create(user: User.find(14), language: Language.find(3))
Langlink.create(user: User.find(14), language: Language.find(6))
Langlink.create(user: User.find(15), language: Language.find(5))
Langlink.create(user: User.find(15), language: Language.find(7))
Langlink.create(user: User.find(15), language: Language.find(8))
Langlink.create(user: User.find(16), language: Language.find(4))
Langlink.create(user: User.find(16), language: Language.find(5))
Langlink.create(user: User.find(16), language: Language.find(6))
Langlink.create(user: User.find(16), language: Language.find(9))
Langlink.create(user: User.find(17), language: Language.find(1))
Langlink.create(user: User.find(17), language: Language.find(10))
Langlink.create(user: User.find(17), language: Language.find(2))
Langlink.create(user: User.find(18), language: Language.find(4))
Langlink.create(user: User.find(18), language: Language.find(9))
Langlink.create(user: User.find(18), language: Language.find(3))
Langlink.create(user: User.find(19), language: Language.find(2))
Langlink.create(user: User.find(19), language: Language.find(1))
Langlink.create(user: User.find(19), language: Language.find(1))
Langlink.create(user: User.find(20), language: Language.find(9))
Langlink.create(user: User.find(20), language: Language.find(8))
Langlink.create(user: User.find(20), language: Language.find(6))
Langlink.create(user: User.find(21), language: Language.find(5))
Langlink.create(user: User.find(21), language: Language.find(3))
Langlink.create(user: User.find(21), language: Language.find(2))
Langlink.create(user: User.find(22), language: Language.find(7))
Langlink.create(user: User.find(22), language: Language.find(9))
Langlink.create(user: User.find(22), language: Language.find(2))


Conversation.create(group: false)
Conversation.create(group: false)
Conversation.create(group: false)

Chatlink.create(user: User.find(1), conversation: Conversation.find(1))
Chatlink.create(user: User.find(2), conversation: Conversation.find(1))
Chatlink.create(user: User.find(3), conversation: Conversation.find(2))
Chatlink.create(user: User.find(4), conversation: Conversation.find(2))
Chatlink.create(user: User.find(5), conversation: Conversation.find(3))
Chatlink.create(user: User.find(1), conversation: Conversation.find(3))

Message.create(body: "Hi!", conversation: Conversation.find(1), user: User.find(1), read: true)
Message.create(body: "Hey Dude hows it going?", conversation: Conversation.find(1), user: User.find(2), read: false)
